<?php

namespace hypeJunction\Scraper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 16:34:38.
 */
class HasherTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Hasher
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = $this->getMockBuilder('hypeJunction\\Scraper\\Hasher')->disableOriginalConstructor()->getMock();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers hypeJunction\Scraper\Hasher::hash
	 * @todo   Implement testHash().
	 */
	public function testHash() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Hasher::getHashFromURL
	 * @todo   Implement testGetHashFromURL().
	 */
	public function testGetHashFromURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Hasher::getURLFromHash
	 * @todo   Implement testGetURLFromHash().
	 */
	public function testGetURLFromHash() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Hasher::getMetaFromURL
	 * @todo   Implement testGetMetaFromURL().
	 */
	public function testGetMetaFromURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
