<?php

namespace hypeJunction\Scraper\Qualifiers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 16:34:40.
 */
class QualifierTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Qualifier
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Qualifier;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers hypeJunction\Scraper\Qualifiers\Qualifier::linkify
	 * @todo   Implement testLinkify().
	 */
	public function testLinkify() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Qualifiers\Qualifier::getBaseUri
	 * @todo   Implement testGetBaseUri().
	 */
	public function testGetBaseUri() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Qualifiers\Qualifier::getHref
	 * @todo   Implement testGetHref().
	 */
	public function testGetHref() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
