<?php

namespace hypeJunction\Scraper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 16:34:42.
 */
class EmbedderTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Embedder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Embedder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::getEmbedView
	 * @todo   Implement testGetEmbedView().
	 */
	public function testGetEmbedView() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::setURL
	 * @todo   Implement testSetURL().
	 */
	public function testSetURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::getURL
	 * @todo   Implement testGetURL().
	 */
	public function testGetURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::setEntity
	 * @todo   Implement testSetEntity().
	 */
	public function testSetEntity() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::getEntity
	 * @todo   Implement testGetEntity().
	 */
	public function testGetEntity() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::getMeta
	 * @todo   Implement testGetMeta().
	 */
	public function testGetMeta() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::extractMeta
	 * @todo   Implement testExtractMeta().
	 */
	public function testExtractMeta() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::getType
	 * @todo   Implement testGetType().
	 */
	public function testGetType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Embedder::getView
	 * @todo   Implement testGetView().
	 */
	public function testGetView() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
