<?php

namespace hypeJunction\Scraper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 16:34:35.
 */
class MetaHandlerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var MetaHandler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MetaHandler;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers hypeJunction\Scraper\MetaHandler::fromArray
	 * @todo   Implement testFromArray().
	 */
	public function testFromArray() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
