<?php

namespace hypeJunction\Scraper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 16:34:39.
 */
class ShortenerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Shortener
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Shortener;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers hypeJunction\Scraper\Shortener::shorten
	 * @todo   Implement testShorten().
	 */
	public function testShorten() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Shortener::getShortURL
	 * @todo   Implement testGetShortURL().
	 */
	public function testGetShortURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
