<?php

namespace hypeJunction\Scraper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 16:34:38.
 */
class UrlHandlerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var UrlHandler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new UrlHandler;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::getURL
	 * @todo   Implement testGetURL().
	 */
	public function testGetURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::isValid
	 * @todo   Implement testIsValid().
	 */
	public function testIsValid() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::isImageFile
	 * @todo   Implement testIsImageFile().
	 */
	public function testIsImageFile() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::isReachable
	 * @todo   Implement testIsReachable().
	 */
	public function testIsReachable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::getMeta
	 * @todo   Implement testGetMeta().
	 */
	public function testGetMeta() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::isInSite
	 * @todo   Implement testIsInSite().
	 */
	public function testIsInSite() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::getEntity
	 * @todo   Implement testGetEntity().
	 */
	public function testGetEntity() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\UrlHandler::getContentType
	 * @todo   Implement testGetContentType().
	 */
	public function testGetContentType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
