<?php

namespace hypeJunction\Scraper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 16:34:43.
 */
class ValidatorTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Validator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Validator;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers hypeJunction\Scraper\Validator::isValidURL
	 * @todo   Implement testIsValidURL().
	 */
	public function testIsValidURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers hypeJunction\Scraper\Validator::isImage
	 * @todo   Implement testIsImage().
	 */
	public function testIsImage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
